default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_P8_KEY"],
      is_key_content_base64: false,
      in_house: false
    )

    setup_ci

    match(
      type: "appstore",
      readonly: false,
      git_url: "git@github.com:usecomus-afk/purelyistanbul-certs.git",
      app_identifier: "com.usecomus.olympus",
      username: "fastlane"
    )

    update_project_provisioning(
      xcodeproj: "ios/App/App.xcodeproj",
      profile: ENV["sigh_com.usecomus.olympus_appstore_profile-path"],
      build_configuration: "Release"
    )

    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"],
      xcodeproj: "ios/App/App.xcodeproj"
    )

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "purelyistanbul.ipa"
    )

    upload_to_testflight(
      ipa: "./build/purelyistanbul.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
