default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_P8_KEY"],
      is_key_content_base64: false,
      in_house: false
    )

    setup_ci

    get_certificates
    get_provisioning_profile(app_identifier: "com.usecomus.olympus")

    update_project_team(
      path: "ios/App/App.xcodeproj",
      teamid: "R8LQC6KZG8"
    )

    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"],
      xcodeproj: "ios/App/App.xcodeproj"
    )

    build_app(
      project: "ios/App/App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "purelyistanbul.ipa",
      xcargs: "DEVELOPMENT_TEAM=R8LQC6KZG8 CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=\"Apple Distribution\""
    )

    upload_to_testflight(
      ipa: "./build/purelyistanbul.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
