import type { GroupType, MarketplaceListing } from './types';

const now = new Date().toISOString();

function createRealListing(data: {
  id: string;
  type: 'stay' | 'experience';
  title: string;
  description: string;
  category: string;
  district: string;
  pricing: { basePrice: number; currency: string; cleaningFee?: number };
  capacity: number;
  amenities: string[];
  coverImageUrl: string;
  galleryUrls?: string[];
}): MarketplaceListing {
  const images = (
    data.galleryUrls && data.galleryUrls.length > 0
      ? data.galleryUrls
      : [data.coverImageUrl]
  ).map((url) => ({ url, path: url }));

  return {
    id: data.id,
    type: data.type,
    title: data.title,
    description: data.description,
    categoryId: data.category,
    category: data.category,
    district: data.district,
    neighborhood: data.district,
    address: data.district,
    coordinates: { lat: 41.0082, lng: 28.9784 },
    pricing: data.pricing,
    rating: {
      score: 4.8 + (Math.random() * 0.2),
      reviewCount: Math.floor(Math.random() * 200) + 50,
    },
    features: {
      capacity: data.capacity,
      bedrooms: 0,
      bathrooms: 0,
      amenities: data.amenities,
    },
    images,
    coverImage: data.coverImageUrl,
    host: {
      id: 'purely-host',
      name: 'purelyistanbul',
      isSuperhost: true,
      avatarUrl: '/logo-icon.png',
      joinDate: '2024-01-01',
    },
    status: 'active',
    createdAt: now,
    updatedAt: now,
  };
}

export const SEED_LISTINGS: MarketplaceListing[] = [
  createRealListing({
    id: "exp-1",
    type: 'experience',
    title: `Bosphorus Dinner Cruise & Shows`,
    description: `TÜRSAB A Grubu, yüksek kapasiteli yemekli Boğaz turu`,
    category: "cat-1",
    district: "Karaköy / Kabataş",
    pricing: { basePrice: 65, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-1.jpg"
  }),
  createRealListing({
    id: "exp-2",
    type: 'experience',
    title: `All-Inclusive Dinner Cruise with Show`,
    description: `Semazen, folklor ve oryantal gösterili gece turu`,
    category: "cat-1",
    district: "Kabataş İskelesi",
    pricing: { basePrice: 65, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-2.jpg"
  }),
  createRealListing({
    id: "exp-3",
    type: 'experience',
    title: `Bosphorus Turkish Night Dinner Cruise`,
    description: `Yabancı acentelerin en çok tercih ettiği tekne işletmesi`,
    category: "cat-1",
    district: "Kabataş / Beşiktaş",
    pricing: { basePrice: 65, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-3.jpg"
  }),
  createRealListing({
    id: "exp-4",
    type: 'experience',
    title: `Luxury Private Yacht Charter Bosphorus`,
    description: `VIP çiftler ve küçük gruplar için 2-4 saatlik özel yat turu`,
    category: "cat-1",
    district: "Kuruçeşme / Bebek",
    pricing: { basePrice: 65, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-4.jpg"
  }),
  createRealListing({
    id: "exp-5",
    type: 'experience',
    title: `Sunset Cruise on Luxury Yacht`,
    description: `Gün batımı canlı rehberli butik tekne turu`,
    category: "cat-1",
    district: "Karaköy İskelesi",
    pricing: { basePrice: 65, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-5.jpg"
  }),
  createRealListing({
    id: "exp-6",
    type: 'experience',
    title: `Basilica Cistern, Topkapi & Hagia Sophia Fast Track`,
    description: `Müze hızlı geçiş ve profesyonel rehberlik paketi`,
    category: "cat-2",
    district: "Sultanahmet, Fatih",
    pricing: { basePrice: 45, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-6.jpg"
  }),
  createRealListing({
    id: "exp-7",
    type: 'experience',
    title: `Small Group Old City Walking Tour`,
    description: `Yarım/tam günlük tarihi yarımada lisanslı rehberlik`,
    category: "cat-2",
    district: "Sultanahmet, Fatih",
    pricing: { basePrice: 45, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-7.jpg"
  }),
  createRealListing({
    id: "exp-8",
    type: 'experience',
    title: `Hidden Gems of Istanbul & Old Town Walk`,
    description: `Butik otel misafirlerine özel kişiselleştirilmiş rotalar`,
    category: "cat-2",
    district: "Karaköy, Beyoğlu",
    pricing: { basePrice: 45, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-8.jpg"
  }),
  createRealListing({
    id: "exp-9",
    type: 'experience',
    title: `Historic Peninsula Daily Guided Tour`,
    description: `Geniş yabancı turist kitlelerine hitap eden şehir yürüyüşleri`,
    category: "cat-2",
    district: "Sultanahmet, Fatih",
    pricing: { basePrice: 45, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-9.jpg"
  }),
  createRealListing({
    id: "exp-10",
    type: 'experience',
    title: `Taste of Two Continents Food Tour`,
    description: `GetYourGuide/TripAdvisor 1 numaralı sokak lezzetleri turu`,
    category: "cat-3",
    district: "Karaköy & Kadıköy",
    pricing: { basePrice: 55, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-10.jpg"
  }),
  createRealListing({
    id: "exp-11",
    type: 'experience',
    title: `Culinary Secrets of the Old City & Kadıköy`,
    description: `Derinlemesine gastronomi ve esnaf lokantaları rotası`,
    category: "cat-3",
    district: "Beyoğlu / Kadıköy",
    pricing: { basePrice: 55, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-11.jpg"
  }),
  createRealListing({
    id: "exp-12",
    type: 'experience',
    title: `Istanbul Historic Food & Market Walk`,
    description: `Küçük gruplu gurme sokak lezzetleri ve tatlı tadımları`,
    category: "cat-3",
    district: "Karaköy / Eminönü",
    pricing: { basePrice: 55, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-12.jpg"
  }),
  createRealListing({
    id: "exp-13",
    type: 'experience',
    title: `Home Cooking Class & Spice Market Tour`,
    description: `Geleneksel Türk yemekleri pişirme atölyesi ve pazar turu`,
    category: "cat-3",
    district: "Nişantaşı, Şişli",
    pricing: { basePrice: 55, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-13.jpg"
  }),
  createRealListing({
    id: "exp-14",
    type: 'experience',
    title: `Traditional Turkish Bath & Massage Ritual`,
    description: `300 yıllık tarihi atmosferde lüks hamam ve masaj`,
    category: "cat-4",
    district: "Sultanahmet, Fatih",
    pricing: { basePrice: 60, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-14.jpg"
  }),
  createRealListing({
    id: "exp-15",
    type: 'experience',
    title: `Authentic Hammam Experience`,
    description: `Mimar Sinan eseri, rezervasyonlu otantik hamam deneyimi`,
    category: "cat-4",
    district: "Karaköy, Beyoğlu",
    pricing: { basePrice: 60, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-15.jpg"
  }),
  createRealListing({
    id: "exp-16",
    type: 'experience',
    title: `Whirling Dervishes & Sema Ceremony`,
    description: `Tarihi hamamda canlı semazen ve ritüel gösterisi`,
    category: "cat-4",
    district: "Sirkeci, Fatih",
    pricing: { basePrice: 60, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-16.jpg"
  }),
  createRealListing({
    id: "exp-17",
    type: 'experience',
    title: `Turkish Mosaic Lamp Making Workshop`,
    description: `Geleneksel mozaik lamba ve ebru el sanatı atölyesi`,
    category: "cat-4",
    district: "Sultanahmet, Fatih",
    pricing: { basePrice: 60, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-17.jpg"
  }),
  createRealListing({
    id: "exp-18",
    type: 'experience',
    title: `Turkish Coffee Making & Fortune Telling`,
    description: `Kumda Türk kahvesi pişirme ve fal kültürü deneyimi`,
    category: "cat-4",
    district: "Sultanahmet, Fatih",
    pricing: { basePrice: 60, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-18.jpg"
  }),
  createRealListing({
    id: "exp-19",
    type: 'experience',
    title: `Full-Day Bursa & Uludağ Cable Car Tour`,
    description: `Bursa teleferik, tarihi camiler ve İskender kebap turu`,
    category: "cat-5",
    district: "Fatih, İstanbul",
    pricing: { basePrice: 110, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-19.jpg"
  }),
  createRealListing({
    id: "exp-20",
    type: 'experience',
    title: `Princes' Islands Full-Day Boat & Guide Tour`,
    description: `Büyükada & Heybeliada rehberli keşif ve öğle yemeği`,
    category: "cat-5",
    district: "Kabataş / Eminönü",
    pricing: { basePrice: 110, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-20.jpg"
  }),
  createRealListing({
    id: "exp-21",
    type: 'experience',
    title: `Sapanca Lake & Maşukiye Nature Day Trip`,
    description: `Doğa yürüyüşü, göl kenarı dinlenme ve şelale gezisi`,
    category: "cat-5",
    district: "Taksim / Fatih",
    pricing: { basePrice: 110, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-21.jpg"
  }),
  createRealListing({
    id: "exp-24",
    type: 'experience',
    title: `IST & SAW Private VIP Airport Transfer`,
    description: `7/24 Mercedes Vito/Sprinter ile otel havalimanı transferi`,
    category: "cat-6",
    district: "İstanbul Genel",
    pricing: { basePrice: 50, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-24.jpg"
  }),
  createRealListing({
    id: "exp-25",
    type: 'experience',
    title: `Chauffeur Driven VIP Car Rental & Transfer`,
    description: `Lüks araç filosu ve şoförlü transfer hizmeti`,
    category: "cat-6",
    district: "Şişli / Taksim",
    pricing: { basePrice: 50, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-25.jpg"
  }),
  createRealListing({
    id: "exp-26",
    type: 'experience',
    title: `Rooftop Flying Dress & Cultural Photoshoot`,
    description: `Tarihi yarımada ve martı manzaralı uçan elbise çekimi`,
    category: "cat-7",
    district: "Süleymaniye, Fatih",
    pricing: { basePrice: 75, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-26.jpg"
  }),
  createRealListing({
    id: "exp-27",
    type: 'experience',
    title: `Galata Tower View Rooftop Photoshoot`,
    description: `Galata Kulesi arka planlı profesyonel fotoğraf çekimi`,
    category: "cat-7",
    district: "Galata, Beyoğlu",
    pricing: { basePrice: 75, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-27.jpg"
  }),
  createRealListing({
    id: "exp-28",
    type: 'experience',
    title: `Authentic Ottoman Costumes & Rooftop Shoot`,
    description: `Geleneksel kıyafetler ve halı konseptli teras çekimleri`,
    category: "cat-7",
    district: "Sultanahmet, Fatih",
    pricing: { basePrice: 75, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-28.jpg"
  }),
  createRealListing({
    id: "exp-29",
    type: 'experience',
    title: `Flying Dress Bosphorus & Ortaköy Shoot`,
    description: `Özel tasarım elbiselerle sosyal medya ve drone video çekimi`,
    category: "cat-7",
    district: "Ortaköy / Galata",
    pricing: { basePrice: 75, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-29.jpg"
  }),
  createRealListing({
    id: "exp-30",
    type: 'experience',
    title: `Guided Nightlife Tour & Free Club Entry`,
    description: `4 farklı mekan, shot ikramları ve güvenli gece kulübü girişi`,
    category: "cat-8",
    district: "Taksim / Kadıköy",
    pricing: { basePrice: 40, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-30.jpg"
  }),
  createRealListing({
    id: "exp-31",
    type: 'experience',
    title: `Bosphorus Party Bus & Bar Hopping`,
    description: `Uluslararası gezginler için parti otobüsü ve bar turu`,
    category: "cat-8",
    district: "Beyoğlu, İstanbul",
    pricing: { basePrice: 40, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-31.jpg"
  }),
  createRealListing({
    id: "exp-32",
    type: 'experience',
    title: `Kadıköy Alternative Nightlife & Craft Beers`,
    description: `Kadıköy barlar sokağı ve yerel pub keşif turu`,
    category: "cat-8",
    district: "Moda / Kadıköy",
    pricing: { basePrice: 40, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-32.jpg"
  }),
  createRealListing({
    id: "exp-33",
    type: 'experience',
    title: `Grand Bazaar Shopping Tour & Local Bargaining`,
    description: `Halı, deri, takı ve baharatta güvenli alışveriş rehberliği`,
    category: "cat-9",
    district: "Beyazıt, Fatih",
    pricing: { basePrice: 50, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-33.jpg"
  }),
  createRealListing({
    id: "exp-34",
    type: 'experience',
    title: `Cukurcuma Antiques & Galata Boutiques Walk`,
    description: `Tasarım dükkanları ve antikacılar için stil danışmanlığı`,
    category: "cat-9",
    district: "Çukurcuma / Nişantaşı",
    pricing: { basePrice: 50, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-34.jpg"
  }),
  createRealListing({
    id: "exp-35",
    type: 'experience',
    title: `Historic Bazaars & Craft Workshops Tour`,
    description: `Geleneksel ustaların atölyelerine özel ziyaretler`,
    category: "cat-9",
    district: "Eminönü, Fatih",
    pricing: { basePrice: 50, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-35.jpg"
  }),
  createRealListing({
    id: "exp-36",
    type: 'experience',
    title: `World's Largest Thematic Aquarium Ticket`,
    description: `17 tema, yağmur ormanı ve 17.000+ deniz canlısı`,
    category: "cat-10",
    district: "Florya, Bakırköy",
    pricing: { basePrice: 35, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-36.jpg"
  }),
  createRealListing({
    id: "exp-37",
    type: 'experience',
    title: `Theme Park & Entertainment Center Ticket`,
    description: `Nefeskesen hız treni ve aile boyu tematik lunapark`,
    category: "cat-10",
    district: "Eyüpsultan, İstanbul",
    pricing: { basePrice: 35, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-37.jpg"
  }),
  createRealListing({
    id: "exp-38",
    type: 'experience',
    title: `Industrial & Transport Interactive Museum`,
    description: `Klasik araçlar, denizaltı ve interaktif bilim atölyeleri`,
    category: "cat-10",
    district: "Hasköy, Beyoğlu",
    pricing: { basePrice: 35, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-38.jpg"
  }),
  createRealListing({
    id: "exp-39",
    type: 'experience',
    title: `Open-Air Miniature Park Ticket & Tour`,
    description: `Türkiye ve Osmanlı coğrafyası 1/25 ölçekli mimari maketleri`,
    category: "cat-10",
    district: "Sütlüce, Beyoğlu",
    pricing: { basePrice: 35, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-39.jpg"
  }),
  createRealListing({
    id: "exp-40",
    type: 'experience',
    title: `Optical Illusions & Vortex Tunnel Experience`,
    description: `İnteraktif optik illüzyon odaları ve aile eğlencesi`,
    category: "cat-10",
    district: "İstiklal / Emaar",
    pricing: { basePrice: 35, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-40.jpg"
  }),
  createRealListing({
    id: "exp-41",
    type: 'experience',
    title: `Contemporary Art Exhibition & Audio Guide`,
    description: `Renzo Piano tasarımı binada Türkiye'nin ilk modern sanat müzesi`,
    category: "cat-11",
    district: "Karaköy / Galataport",
    pricing: { basePrice: 40, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-41.jpg"
  }),
  createRealListing({
    id: "exp-42",
    type: 'experience',
    title: `Orientalist Paintings & Kütahya Tiles Exhibition`,
    description: `Kaplumbağa Terbiyecisi ve dönemsel çağdaş sergiler`,
    category: "cat-11",
    district: "Tepebaşı, Beyoğlu",
    pricing: { basePrice: 40, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-42.jpg"
  }),
  createRealListing({
    id: "exp-43",
    type: 'experience',
    title: `Modern Art Exhibitions & Guided Gallery Tours`,
    description: `Çağdaş sanat sergileri, mimari yapı ve heykel galerileri`,
    category: "cat-11",
    district: "Dolapdere, Beyoğlu",
    pricing: { basePrice: 40, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-43.jpg"
  }),
  createRealListing({
    id: "exp-44",
    type: 'experience',
    title: `Ottoman Bank Museum & Architectural Tour`,
    description: `Tarihi Fransız mimarisi, araştırma kütüphanesi ve sergiler`,
    category: "cat-11",
    district: "Bankalar Cd., Karaköy",
    pricing: { basePrice: 40, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-44.jpg"
  }),
  createRealListing({
    id: "exp-45",
    type: 'experience',
    title: `Sufi Heritage & Mevlevi Lodges Tour`,
    description: `İstanbul'un en eski Mevlevihanesi ve derviş kültürü`,
    category: "cat-12",
    district: "Tünel / Galata",
    pricing: { basePrice: 45, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-45.jpg"
  }),
  createRealListing({
    id: "exp-46",
    type: 'experience',
    title: `Ecumenical Patriarchate & Byzantine Heritage`,
    description: `Aya Yorgi Kilisesi ve Fener-Balat Hristiyan mirası rotası`,
    category: "cat-12",
    district: "Fener, Fatih",
    pricing: { basePrice: 45, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-46.jpg"
  }),
  createRealListing({
    id: "exp-47",
    type: 'experience',
    title: `Jewish Heritage & Synagogues Guided Tour`,
    description: `Tarihi Neve Şalom Sinagogu ve Sefarad Yahudi tarihi`,
    category: "cat-12",
    district: "Karaköy / Beyoğlu",
    pricing: { basePrice: 45, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-47.jpg"
  }),
  createRealListing({
    id: "exp-48",
    type: 'experience',
    title: `Private Synagogue & Heritage Walking Tour`,
    description: `Özel izinli tarihi sinagoglar ve kültür yürüyüşleri`,
    category: "cat-12",
    district: "Balat / Galata",
    pricing: { basePrice: 45, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-48.jpg"
  }),
  createRealListing({
    id: "exp-49",
    type: 'experience',
    title: `Kitesurf & Windsurf Lessons in Black Sea`,
    description: `Kilyos sahilinde dalga sörfü, rüzgar sörfü ve SUP kiralama`,
    category: "cat-13",
    district: "Kilyos, Sarıyer",
    pricing: { basePrice: 50, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-49.jpg"
  }),
  createRealListing({
    id: "exp-50",
    type: 'experience',
    title: `Belgrad Forest ATV Quad Safari & Nature Tour`,
    description: `Orman içi rehberli ATV safari ve açık hava macerası`,
    category: "cat-13",
    district: "Belgrad Ormanı, Sarıyer",
    pricing: { basePrice: 50, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-50.jpg"
  }),
  createRealListing({
    id: "exp-51",
    type: 'experience',
    title: `Princes' Islands Guided E-Bike & Nature Ride`,
    description: `Adanın tarihi köşkleri ve koylarında rehberli elektrikli bisiklet turu`,
    category: "cat-13",
    district: "Büyükada, Adalar",
    pricing: { basePrice: 50, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-51.jpg"
  }),
  createRealListing({
    id: "exp-52",
    type: 'experience',
    title: `High Ropes Course & Zipline Adventure`,
    description: `Orman içi yüksek ip parkuru ve zipline aktivitesi`,
    category: "cat-13",
    district: "Ayazağa, Sarıyer",
    pricing: { basePrice: 50, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-52.jpg"
  }),
  createRealListing({
    id: "rest-1",
    type: 'experience',
    title: `Deraliye Rooftop Restaurant`,
    description: `Ayasofya ve Sultanahmet silüetine bakan tarihi terasında 15. ve 17. yüzyıl Osmanlı padişah ziyafet reçetelerini orijinal sunumlarıyla servis eden ödüllü fine-dining deneyimi.`,
    category: "cat-14",
    district: "Alemdar Mah., Ticarethane Sk. No:10, Sultanahmet / Fatih",
    pricing: { basePrice: 1200, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-2",
    type: 'experience',
    title: `Hidden Garden Restaurant`,
    description: `Tarihi Sultanahmet sokakları arasında yeşillikler içindeki gizli avlusunda ateş şovlu testi kebabı ve taze deniz ürünleri sunan, uluslararası turistlerin 1 numaralı tercihi.`,
    category: "cat-14",
    district: "Sultanahmet Mah., Akbıyık Cd. No:24, Fatih / İstanbul",
    pricing: { basePrice: 650, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-3",
    type: 'experience',
    title: `Loti Restaurant & Rooftop`,
    description: `Panoramik Marmara Denizi ve Tarihi Yarımada manzarası eşliğinde lüks servis, geniş şarap kavı ve imza kokteyller sunan şık teras restoranı.`,
    category: "cat-14",
    district: "Binbirdirek Mah., Peykhane Cd. No:16, Sultanahmet / Fatih",
    pricing: { basePrice: 950, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-4",
    type: 'experience',
    title: `AŞEKA Karaköy`,
    description: `100 yıllık tarihi taş binada modern sanat ile harmanlanmış şef tabakları, avangart mutfak teknikleri ve özel kokteyl barı.`,
    category: "cat-14",
    district: "Müeyyetzade Mah., Arap Oğlan Sk. No:6, Karaköy / Beyoğlu",
    pricing: { basePrice: 1400, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-5",
    type: 'experience',
    title: `Mikla Restaurant (1 Michelin Yıldızı)`,
    description: `Şef Mehmet Gürs liderliğinde Anadolu’nun yerel üreticilerinden toplanan malzemelerin çağdaş iskandinav-türk teknikleriyle sunulduğu, Boğaz ve Haliç manzaralı ikonik teras.`,
    category: "cat-14",
    district: "The Marmara Pera, Meşrutiyet Cd. No:15, Tepebaşı / Beyoğlu",
    pricing: { basePrice: 2800, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-6",
    type: 'experience',
    title: `Pandeli Restaurant`,
    description: `Audrey Hepburn’den Kraliçe II. Elizabeth’e kadar dünya liderlerini ağırlamış, Mısır Çarşısı'nın turkuaz çinileriyle bezeli 120 yıllık yaşayan gastronomi efsanesi.`,
    category: "cat-14",
    district: "Mısır Çarşısı İçi 1. Kat No:1, Eminönü / Fatih",
    pricing: { basePrice: 750, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-7",
    type: 'experience',
    title: `Neolokal (1 Michelin Yıldızı & Michelin Yeşil Yıldız)`,
    description: `Şef Maksut Aşkar imzasıyla SALT Galata çatısında sürdürülebilir yerel malzemelerle hazırlanan, Tarihi Yarımada'ya bakan büyüleyici şef restoranı.`,
    category: "cat-14",
    district: "SALT Galata, Bankalar Cd. No:11, Karaköy / Beyoğlu",
    pricing: { basePrice: 2600, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-8",
    type: 'experience',
    title: `Fine Dine İstanbul Rooftop`,
    description: `Ayasofya, Sultanahmet Camii ve Boğaz hattını aynı karede 360 derece kesintisiz gören en yüksek seyir zevkine sahip fine-dining mekanı.`,
    category: "cat-14",
    district: "Dr. M. Akil Sk. No:19 (Hotel Arcadia Blue 9. Kat), Sultanahmet / Fatih",
    pricing: { basePrice: 1100, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-9",
    type: 'experience',
    title: `Çiya Sofrası`,
    description: `Şef Musa Dağdeviren’in unutulmaya yüz tutmuş yüzlerce yıllık Anadolu ve Mezopotamya reçetelerini yaşattığı, uluslararası belgesellere konu olan lezzet mabedi.`,
    category: "cat-14",
    district: "Caferağa Mah., Güneşli Bahçe Sk. No:43, Kadıköy Çarşı",
    pricing: { basePrice: 550, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-10",
    type: 'experience',
    title: `Matbah Ottoman Palace Cuisine`,
    description: `Topkapı Sarayı'nın yanı başında, Topkapı arşivlerinden çıkarılan aslına uygun malzemeler ve baharatlarla sunulan kraliyet yemek deneyimi.`,
    category: "cat-14",
    district: "Cankurtaran Mah., Caferiye Sk. No:6/1, Sultanahmet / Fatih",
    pricing: { basePrice: 1300, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-11",
    type: 'experience',
    title: `Sunset Grill & Bar`,
    description: `Ulus Parkı tepesinden Boğaz Köprüsü'nü kucaklayan manzarası, uluslararası şarap koleksiyonu ve 30 yıldır değişmeyen elit servis standardı.`,
    category: "cat-14",
    district: "Kuruçeşme Mah., Yol Sk. No:2 Ulus Parkı İçi, Beşiktaş",
    pricing: { basePrice: 2200, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-12",
    type: 'experience',
    title: `Mürver Restaurant`,
    description: `Odun ateşinde ve tütsüleme fırınlarında hazırlanan et ve deniz mahsullerini, Tarihi Yarımada manzaralı çağdaş terasında sunan Michelin tavsiyeli mekan.`,
    category: "cat-14",
    district: "Kemankeş Karamustafa Paşa Mah., Kemankeş Cd. No:57-59 (Novotel Rooftop), Karaköy",
    pricing: { basePrice: 1600, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-13",
    type: 'experience',
    title: `Feriye Lokantası`,
    description: `19. yüzyıl Osmanlı Karakol binasında, Ortaköy Camii ve Boğaz Köprüsü'nün hemen yanı başında denizle sıfır konumda konumlanmış tarihi lezzet sarayı.`,
    category: "cat-14",
    district: "Çırağan Cd. No:44, Ortaköy / Beşiktaş",
    pricing: { basePrice: 1800, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-14",
    type: 'experience',
    title: `Nicole Restaurant (1 Michelin Yıldızı)`,
    description: `Tarihi Soeurs Garde-Malades Manastırı terasında, Adalar'a kadar uzanan manzaraya karşı her 6 haftada bir değişen gurme tadım menüsü.`,
    category: "cat-14",
    district: "Tomtom Mah., Boğazkesen Cd. Tomtom Kaptan Sk. No:18, Beyoğlu",
    pricing: { basePrice: 2900, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-15",
    type: 'experience',
    title: `Nuz Restaurant Garden`,
    description: `Mezopotamya'nın bin yıllık baharat kültürünü ve otantik güveç yemeklerini samimi bir bahçe atmosferinde sunan gastronomi durağı.`,
    category: "cat-14",
    district: "Küçük Ayasofya Mah., Mustafa Paşa Sk. No:34, Sultanahmet / Fatih",
    pricing: { basePrice: 650, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-16",
    type: 'experience',
    title: `Beyoğlu Ocakbaşı`,
    description: `Köz başında gözünüzün önünde pişen taze kuzu etleri ve çıtır lavaşlarıyla İstiklal Caddesi civarının en popüler otantik ocakbaşı deneyimi.`,
    category: "cat-14",
    district: "Şehit Muhtar Mah., Bekar Sk. No:18, Taksim / Beyoğlu",
    pricing: { basePrice: 600, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-17",
    type: 'experience',
    title: `Galata Meyhanesi`,
    description: `Mikrofon kullanılmadan icra edilen akustik fasıl nameleri eşliğinde klasik Boğaziçi ve Rum meze kültürünü yaşatan otantik meyhane.`,
    category: "cat-14",
    district: "Asmalı Mescit Mah., Meşrutiyet Cd. No:80, Beyoğlu",
    pricing: { basePrice: 850, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-18",
    type: 'experience',
    title: `Hane Kadıköy`,
    description: `Kadıköy’ün enerjik atmosferinde Ege otları, modern deniz mezeleri ve keyifli müziklerle dolu genç ve dinamik gastronomi noktası.`,
    category: "cat-14",
    district: "Caferağa Mah., Muvakkithane Cd. No:14, Kadıköy",
    pricing: { basePrice: 800, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-19",
    type: 'experience',
    title: `Ala Kadıköy Meyhane`,
    description: `Nostaljik taş plak müzikleri ve Girit göçmenlerinin elinden çıkan otantik zeytinyağlı mezelerle Kadıköy balıkçılar çarşısının köklü mekanı.`,
    category: "cat-14",
    district: "Osmanağa Mah., Kırtasiyeci Sk. No:20, Kadıköy",
    pricing: { basePrice: 700, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "rest-20",
    type: 'experience',
    title: `Tarihi Sultanahmet Köftecisi (1920 Selim Usta)`,
    description: `1920'den bu yana baharatsız, sadece saf dana-kuzu eti ve tuzla hazırlanan formülüyle Sultanahmet meydanının en köklü ve ünlü lezzet durağı.`,
    category: "cat-14",
    district: "Alemdar Mah., Divanyolu Cd. No:12, Sultanahmet / Fatih",
    pricing: { basePrice: 350, currency: "TRY" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "exp-aesthetic-1",
    type: 'experience',
    title: `Nişantaşı Glow & Fraksiyonel Cilt Yenileme`,
    description: `Sıfır İyileşme Süresi (Zero Downtime), FDA Onaylı Cihazlar, Çok Dilli Medikal Konsiyerj, Otel Transfer Desteği`,
    category: "cat-15",
    district: "Abdi İpekçi Cad., Nişantaşı / Şişli",
    pricing: { basePrice: 180, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-aesthetic-1.jpg"
  }),
  createRealListing({
    id: "exp-aesthetic-2",
    type: 'experience',
    title: `Deep Clean HydraFacial & Leke Tedavisi`,
    description: `Vakumlu Vortex Teknolojisi, Cilt Tipi Analizi, Aynı Gün Şehri Gezmeye Devam Edebilme, Anında Canlılık`,
    category: "cat-15",
    district: "Mecidiyeköy & Nişantaşı / Şişli",
    pricing: { basePrice: 90, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-aesthetic-2.jpg"
  }),
  createRealListing({
    id: "exp-aesthetic-3",
    type: 'experience',
    title: `Organik Saç & Yüz Mezoterapisi`,
    description: `Kişiye Özel Biyo-Kokteyller, İnce Çizgi ve Gözenek Sıkılaştırma, VIP Lounge ve Karşılama`,
    category: "cat-15",
    district: "Ataşehir & Fulya / Şişli",
    pricing: { basePrice: 250, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-aesthetic-3.jpg"
  }),
  createRealListing({
    id: "exp-aesthetic-4",
    type: 'experience',
    title: `Safir FUE & DHI Saç Restorasyonu`,
    description: `Doğal Ön Saç Çizgisi Tasarımı, Maksimum Greft Garantisi, 12 Aylık Dijital Uzaktan Takip`,
    category: "cat-15",
    district: "Finans Merkezi Aksı, Ümraniye / Ataşehir",
    pricing: { basePrice: 1750, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "exp-aesthetic-5",
    type: 'experience',
    title: `Baby Botox & Doğal Dudak Dolgusu`,
    description: `Mimikleri Dondurmayan Doğal Sonuçlar, Orijinal FDA Onaylı Dolgu Maddeleri, 15 Dakikalık Pratik Uygulama`,
    category: "cat-15",
    district: "Altunizade / Üsküdar",
    pricing: { basePrice: 220, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "/images/experiences/exp-aesthetic-5.jpg"
  }),
  createRealListing({
    id: "exp-aesthetic-6",
    type: 'experience',
    title: `Lüks Oksijen & Anti-Stress Cilt Detoksu`,
    description: `Saf Oksijen İnfüzyonu, JCI Akreditasyonlu Hastane Standartları, Zorlu Center VIP Lokasyonu`,
    category: "cat-15",
    district: "Zorlu Center, Beşiktaş",
    pricing: { basePrice: 320, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "exp-aesthetic-7",
    type: 'experience',
    title: `Hollywood Smile & Dijital Gülüş Tasarımı`,
    description: `3D CAD/CAM Ağız İçi Tarama, 5-7 Günde Hızlı Teslimat, VIP Havalimanı Karşılama, Çok Dilli Tercüman`,
    category: "cat-15",
    district: "Fulya, Şişli / İstanbul",
    pricing: { basePrice: 2200, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "exp-aesthetic-8",
    type: 'experience',
    title: `Kapalı & Piezo Ultrasonic Rhinoplasty`,
    description: `Kırmadan Ses Dalgalarıyla Kemik Şekillendirme (Piezo), Minimum Morluk ve Şişlik, Tam Donanımlı A-Plus Hastane`,
    category: "cat-15",
    district: "Terrace Fulya, Şişli / İstanbul",
    pricing: { basePrice: 2800, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "exp-aesthetic-9",
    type: 'experience',
    title: `Vaser Hi-Def Liposuction & Mommy Makeover`,
    description: `Karın Germe, Göğüs Dikleştirme ve Liposuction Kombinasyonu, Özel Hemşire ve Otel Refakati`,
    category: "cat-15",
    district: "Mecidiyeköy / Şişli",
    pricing: { basePrice: 3500, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "exp-aesthetic-10",
    type: 'experience',
    title: `Elit-DHI & İğnesiz Anestezi ile Saç / Sakal Ekimi`,
    description: `Dr. Balwi Patentli Ön Çizgi Protokolü, İğnesiz Comfort Anestezi, Tıraşsız DHI Ekim Seçeneği`,
    category: "cat-15",
    district: "Vadistanbul Aksı, Sarıyer / İstanbul",
    pricing: { basePrice: 1900, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "exp-aesthetic-11",
    type: 'experience',
    title: `Kombine Medikal Estetik (Baby Botox, Jawline & Profhilo)`,
    description: `CE & FDA Onaylı Orijinal Ürün Garantisi, 30 Dakikalık Ekspres Uygulama, İfadeyi Değiştirmeyen Doğal İsviçre/Fransız Dolguları`,
    category: "cat-15",
    district: "Valikonağı Cad., Nişantaşı / Şişli",
    pricing: { basePrice: 350, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=80"
  }),
  createRealListing({
    id: "exp-aesthetic-12",
    type: 'experience',
    title: `Anti-Aging, IV Glutatyon / NAD+ Terapi & Bütünsel Detoks`,
    description: `Hücresel Yenilenme (Anti-Aging IV), Jet-Lag ve Karaciğer Detoksu, Kızılötesi Sauna ve Ozon Terapisi`,
    category: "cat-15",
    district: "Akatlar, Beşiktaş / İstanbul",
    pricing: { basePrice: 280, currency: "EUR" },
    capacity: 10,
    amenities: ["Rehber", "Transfer", "Bilet"],
    coverImageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80"
  })
];
